##################################################
## Prerequisites:
## - $DOCKER_USERNAME and $DOCKER_PASSWORD must
##   be set in the project settings in Travis-CI
##   and their values must be properly escaped
##   for bash.
##   and $APP_NAME
## - $DOCKERHUB_ORGANIZATION must be set in the
##   project settings in Travis-CI. This should
##   be the organization or user to use for
##   publishing images.
##################################################
sudo: required
language: bash
services:
  - docker
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    # Used for specifying the build context relative to this file
    # Likely, this is "."
    - CONTEXT_RELATIVE_PATH=.

    # Relative path from $CONTEXT_RELATIVE_PATH to target Dockerfile
    # Examples: "src/App/Dockerfile", "Dockerfile"
    - DOCKERFILE_RELATIVE_PATH=.docker/Dockerfile

    # Image name and tag used for CI only
    - CI_IMAGE=${APP_NAME}:ci #DO NOT CHANGE

    # Published image base name (user/image) without tag
    # Correct tag is added later
    - BASE_IMAGE=${DOCKER_USERNAME}/${APP_NAME} #DO NOT CHANGE
    - BUILD_PLATFROM=linux/arm,linux/arm64,linux/amd64

before_install:
#  - './.travis/docker_upgrade.sh'
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - sudo apt-get install -y qemu-user-static
  - sudo apt-get install -y binfmt-support
script:
  - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx version
#  - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
#  - docker buildx create --name mybuilder
#  - docker buildx use mybuilder
#  - docker buildx inspect --bootstrap
#  - docker buildx build $CONTEXT_RELATIVE_PATH --platform=$BUILD_PLATFROM -t $CI_IMAGE  -f $DOCKERFILE_RELATIVE_PATH
after_success:
  # Tag pull request builds with ":pr-XXX" where "XXX" is the pull request number
  - |
    if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      docker tag $CI_IMAGE ${DOCKERHUB_ORGANIZATION}/${APP_NAME}:pr-${TRAVIS_PULL_REQUEST};
      docker push ${DOCKERHUB_ORGANIZATION}/${APP_NAME}:pr-${TRAVIS_PULL_REQUEST}
    fi
  # Tag git tag builds with the git tag
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      docker tag $CI_IMAGE ${DOCKERHUB_ORGANIZATION}/${APP_NAME}:${TRAVIS_TAG}
      docker push ${DOCKERHUB_ORGANIZATION}/${APP_NAME}:${TRAVIS_TAG}
    fi
  # Tag pushes on master with ":latest"
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      docker tag $CI_IMAGE ${DOCKERHUB_ORGANIZATION}/${APP_NAME}:latest
      docker push ${DOCKERHUB_ORGANIZATION}/${APP_NAME}:latest
      docker run -v $PWD:/workspace \
        -e DOCKERHUB_USERNAME=$DOCKER_USERNAME \
        -e DOCKERHUB_PASSWORD=$DOCKER_PASSWORD \
        -e DOCKERHUB_REPOSITORY=${DOCKERHUB_ORGANIZATION}/${APP_NAME} \
        -e README_FILEPATH='/workspace/README-DOCKERHUB.md' \
        peterevans/dockerhub-description:2.1.0
    fi
notifications:
  email: false